"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w#pkf)w@0zb*^i4h_4ste7(y%$pb8*1v@m%sv0*p*n08(ydsn-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# In production, set to False and configure ALLOWED_HOSTS properly
ALLOWED_HOSTS = ['*']  # Change to specific hosts in production


# ==============================================================================
# SECURITY SETTINGS - Best Practices for Django Applications
# ==============================================================================

# 1. XSS (Cross-Site Scripting) Protection
# Tells the browser to respect the Content-Type header and not try to guess
# the content type, which prevents certain XSS attacks
SECURE_CONTENT_TYPE_NOSNIFF = True

# Enables the browser's XSS filter to block malicious scripts
SECURE_BROWSER_XSS_FILTER = True

# 2. Clickjacking Protection
# Controls how the page can be embedded in frames/iframes
# 'DENY' means the page cannot be displayed in a frame
X_FRAME_OPTIONS = 'DENY'

# 3. HTTPS and Secure Cookies
# IMPORTANT: Ensure HTTPS is used in production (set up TLS certificates).
# Cookies are only sent over HTTPS to protect sensitive session and CSRF tokens.
CSRF_COOKIE_SECURE = True       # Only send CSRF cookie over HTTPS
SESSION_COOKIE_SECURE = True    # Only send session cookie over HTTPS
SECURE_SSL_REDIRECT = True           # Redirect all HTTP requests to HTTPS
# If the app is behind a reverse proxy/load balancer that terminates TLS (e.g., Heroku, nginx),
# ensure the proxy sets the 'X-Forwarded-Proto' header. Django can use that header to detect secure requests:
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# 4. CSRF Protection
# CSRF tokens are required for all POST, PUT, DELETE requests
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to access CSRF token when needed
CSRF_USE_SESSIONS = False      # Store CSRF tokens in cookies (default)

# 5. Session Security
SESSION_COOKIE_AGE = 1209600   # Session timeout: 2 weeks (in seconds)
SESSION_COOKIE_HTTPONLY = True # Prevent JavaScript from accessing session cookies
SESSION_SAVE_EVERY_REQUEST = False

# 6. Security Headers
# Set Strict-Transport-Security header to enforce HTTPS
SECURE_HSTS_SECONDS = 31536000  # 1 year - instruct browsers to use only HTTPS
SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # Apply HSTS to all subdomains
SECURE_HSTS_PRELOAD = True  # Allow site to be included in browser preload lists

# 7. Password Hashing
# Use strong password hashing algorithm
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]


# ==============================================================================
# CONTENT SECURITY POLICY (CSP)
# ==============================================================================
# CSP helps prevent XSS attacks by specifying which domains can load content
# Set the CSP header to restrict content sources

CSP_DEFAULT_SRC = ("'self'",)  # Only allow resources from same origin by default
CSP_SCRIPT_SRC = ("'self'",)  # Only allow scripts from same origin
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'")  # Allow inline CSS (can be restricted further)
CSP_IMG_SRC = ("'self'", "data:")  # Allow images from same origin and data URIs
CSP_FONT_SRC = ("'self'",)  # Only allow fonts from same origin
CSP_CONNECT_SRC = ("'self'",)  # Only allow connections to same origin
CSP_FRAME_ANCESTORS = ("'none'",)  # Prevent framing (same as X-Frame-Options: DENY)
CSP_FRAME_SRC = ("'self'",)  # Only allow frames from same origin
CSP_OBJECT_SRC = ("'none'",)  # Disable Flash and other plugins

# For development, use report-only mode to see violations without blocking
# For production, change to enforce mode by removing -report-only

# Add trusted CDNs if needed (example):
# CSP_SCRIPT_SRC = ("'self'", "https://cdn.example.com")
# CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "https://cdn.example.com")

# Option to add nonce for inline scripts (advanced, requires template changes)
# CSP_SCRIPT_SRC = ("'self'", "'nonce-{{ request.csp_nonce }}'")

# Report CSP violations to a URL (optional)
# CSP_REPORT_URI = "/csp-report/"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'bookshelf',
    'relationship_app'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.csrf',  # CSRF token context
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Custom User Model Configuration
# Point to the custom user model in bookshelf app
AUTH_USER_MODEL = 'bookshelf.CustomUser'


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
